server:
  port: 8080

spring:
  application:
    name: spring-ai-alibaba-dashscope

  ai:
    dashscope:
      api-key: ${AI_DASHSCOPE_API_KEY}
      chat:
        options:
          model: ${AI_DASHSCOPE_API_MODEL}
