server:
  port: 8080

spring:
  application:
    name: spring-ai-alibaba-openai

  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: ${OPENAI_API_MODEL}
      base-url: https://dashscope.aliyuncs.com/compatible-mode/